# Generated by Django 4.1.1 on 2022-10-02 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section1Title', models.CharField(blank=True, max_length=200, null=True)),
                ('section1Description', models.TextField(blank=True, null=True)),
                ('callToAction', models.CharField(blank=True, max_length=100, null=True)),
                ('section1Image', models.ImageField(default='default.jpg', upload_to='landing_page_images')),
                ('section3Title', models.CharField(blank=True, max_length=200, null=True)),
                ('section3Description', models.TextField(blank=True, null=True)),
                ('section3Image', models.ImageField(default='default.jpg', upload_to='landing_page_images')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.profile')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.website')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='landing_page_images')),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.profile')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.website')),
            ],
        ),
    ]
